spring:
  application:
    name: eureka-server
server:
  port: 10001
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka/
#  client:
#    register-with-eureka: false
#    fetch-registry: false
